package com.heaven.bean;

import java.util.Date;

public class Announcement {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column announcement.id
     *
     * @mbg.generated Thu May 09 23:50:36 CST 2019
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column announcement.name
     *
     * @mbg.generated Thu May 09 23:50:36 CST 2019
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column announcement.author
     *
     * @mbg.generated Thu May 09 23:50:36 CST 2019
     */
    private String author;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column announcement.date
     *
     * @mbg.generated Thu May 09 23:50:36 CST 2019
     */
    private Date date;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column announcement.recruid_id
     *
     * @mbg.generated Thu May 09 23:50:36 CST 2019
     */
    private Integer recruidId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column announcement.content
     *
     * @mbg.generated Thu May 09 23:50:36 CST 2019
     */
    private String content;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column announcement.id
     *
     * @return the value of announcement.id
     *
     * @mbg.generated Thu May 09 23:50:36 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column announcement.id
     *
     * @param id the value for announcement.id
     *
     * @mbg.generated Thu May 09 23:50:36 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column announcement.name
     *
     * @return the value of announcement.name
     *
     * @mbg.generated Thu May 09 23:50:36 CST 2019
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column announcement.name
     *
     * @param name the value for announcement.name
     *
     * @mbg.generated Thu May 09 23:50:36 CST 2019
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column announcement.author
     *
     * @return the value of announcement.author
     *
     * @mbg.generated Thu May 09 23:50:36 CST 2019
     */
    public String getAuthor() {
        return author;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column announcement.author
     *
     * @param author the value for announcement.author
     *
     * @mbg.generated Thu May 09 23:50:36 CST 2019
     */
    public void setAuthor(String author) {
        this.author = author == null ? null : author.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column announcement.date
     *
     * @return the value of announcement.date
     *
     * @mbg.generated Thu May 09 23:50:36 CST 2019
     */
    public Date getDate() {
        return date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column announcement.date
     *
     * @param date the value for announcement.date
     *
     * @mbg.generated Thu May 09 23:50:36 CST 2019
     */
    public void setDate(Date date) {
        this.date = date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column announcement.recruid_id
     *
     * @return the value of announcement.recruid_id
     *
     * @mbg.generated Thu May 09 23:50:36 CST 2019
     */
    public Integer getRecruidId() {
        return recruidId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column announcement.recruid_id
     *
     * @param recruidId the value for announcement.recruid_id
     *
     * @mbg.generated Thu May 09 23:50:36 CST 2019
     */
    public void setRecruidId(Integer recruidId) {
        this.recruidId = recruidId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column announcement.content
     *
     * @return the value of announcement.content
     *
     * @mbg.generated Thu May 09 23:50:36 CST 2019
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column announcement.content
     *
     * @param content the value for announcement.content
     *
     * @mbg.generated Thu May 09 23:50:36 CST 2019
     */
    public void setContent(String content) {
        this.content = content == null ? null : content.trim();
    }

	@Override
	public String toString() {
		return "Announcement [id=" + id + ", name=" + name + ", author=" + author + ", date=" + date + ", recruidId="
				+ recruidId + ", content=" + content + "]";
	}
    
}