package com.heaven.bean;

public class Banner {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column banner.id
     *
     * @mbg.generated Mon Jun 03 09:03:09 CST 2019
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column banner.image
     *
     * @mbg.generated Mon Jun 03 09:03:09 CST 2019
     */
    private String image;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column banner.img_page
     *
     * @mbg.generated Mon Jun 03 09:03:09 CST 2019
     */
    private String imgPage;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column banner.id
     *
     * @return the value of banner.id
     *
     * @mbg.generated Mon Jun 03 09:03:09 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column banner.id
     *
     * @param id the value for banner.id
     *
     * @mbg.generated Mon Jun 03 09:03:09 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column banner.image
     *
     * @return the value of banner.image
     *
     * @mbg.generated Mon Jun 03 09:03:09 CST 2019
     */
    public String getImage() {
        return image;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column banner.image
     *
     * @param image the value for banner.image
     *
     * @mbg.generated Mon Jun 03 09:03:09 CST 2019
     */
    public void setImage(String image) {
        this.image = image == null ? null : image.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column banner.img_page
     *
     * @return the value of banner.img_page
     *
     * @mbg.generated Mon Jun 03 09:03:09 CST 2019
     */
    public String getImgPage() {
        return imgPage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column banner.img_page
     *
     * @param imgPage the value for banner.img_page
     *
     * @mbg.generated Mon Jun 03 09:03:09 CST 2019
     */
    public void setImgPage(String imgPage) {
        this.imgPage = imgPage == null ? null : imgPage.trim();
    }
}