package com.heaven.bean;

import java.util.Date;

public class General {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column general.id
     *
     * @mbg.generated Sat Jun 01 18:07:48 CST 2019
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column general.title
     *
     * @mbg.generated Sat Jun 01 18:07:48 CST 2019
     */
    private String title;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column general.author
     *
     * @mbg.generated Sat Jun 01 18:07:48 CST 2019
     */
    private String author;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column general.date
     *
     * @mbg.generated Sat Jun 01 18:07:48 CST 2019
     */
    private Date date;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column general.start_date
     *
     * @mbg.generated Sat Jun 01 18:07:48 CST 2019
     */
    private Date startDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column general.end_date
     *
     * @mbg.generated Sat Jun 01 18:07:48 CST 2019
     */
    private Date endDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column general.chara
     *
     * @mbg.generated Sat Jun 01 18:07:48 CST 2019
     */
    private String chara;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column general.people_num
     *
     * @mbg.generated Sat Jun 01 18:07:48 CST 2019
     */
    private String peopleNum;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column general.vocation
     *
     * @mbg.generated Sat Jun 01 18:07:48 CST 2019
     */
    private String vocation;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column general.address
     *
     * @mbg.generated Sat Jun 01 18:07:48 CST 2019
     */
    private String address;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column general.school
     *
     * @mbg.generated Sat Jun 01 18:07:48 CST 2019
     */
    private String school;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column general.email
     *
     * @mbg.generated Sat Jun 01 18:07:48 CST 2019
     */
    private String email;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column general.tel_num
     *
     * @mbg.generated Sat Jun 01 18:07:48 CST 2019
     */
    private String telNum;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column general.content
     *
     * @mbg.generated Sat Jun 01 18:07:48 CST 2019
     */
    private String content;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column general.id
     *
     * @return the value of general.id
     *
     * @mbg.generated Sat Jun 01 18:07:48 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column general.id
     *
     * @param id the value for general.id
     *
     * @mbg.generated Sat Jun 01 18:07:48 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column general.title
     *
     * @return the value of general.title
     *
     * @mbg.generated Sat Jun 01 18:07:48 CST 2019
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column general.title
     *
     * @param title the value for general.title
     *
     * @mbg.generated Sat Jun 01 18:07:48 CST 2019
     */
    public void setTitle(String title) {
        this.title = title == null ? null : title.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column general.author
     *
     * @return the value of general.author
     *
     * @mbg.generated Sat Jun 01 18:07:48 CST 2019
     */
    public String getAuthor() {
        return author;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column general.author
     *
     * @param author the value for general.author
     *
     * @mbg.generated Sat Jun 01 18:07:48 CST 2019
     */
    public void setAuthor(String author) {
        this.author = author == null ? null : author.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column general.date
     *
     * @return the value of general.date
     *
     * @mbg.generated Sat Jun 01 18:07:48 CST 2019
     */
    public Date getDate() {
        return date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column general.date
     *
     * @param date the value for general.date
     *
     * @mbg.generated Sat Jun 01 18:07:48 CST 2019
     */
    public void setDate(Date date) {
        this.date = date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column general.start_date
     *
     * @return the value of general.start_date
     *
     * @mbg.generated Sat Jun 01 18:07:48 CST 2019
     */
    public Date getStartDate() {
        return startDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column general.start_date
     *
     * @param startDate the value for general.start_date
     *
     * @mbg.generated Sat Jun 01 18:07:48 CST 2019
     */
    public void setStartDate(Date startDate) {
        this.startDate = startDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column general.end_date
     *
     * @return the value of general.end_date
     *
     * @mbg.generated Sat Jun 01 18:07:48 CST 2019
     */
    public Date getEndDate() {
        return endDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column general.end_date
     *
     * @param endDate the value for general.end_date
     *
     * @mbg.generated Sat Jun 01 18:07:48 CST 2019
     */
    public void setEndDate(Date endDate) {
        this.endDate = endDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column general.chara
     *
     * @return the value of general.chara
     *
     * @mbg.generated Sat Jun 01 18:07:48 CST 2019
     */
    public String getChara() {
        return chara;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column general.chara
     *
     * @param chara the value for general.chara
     *
     * @mbg.generated Sat Jun 01 18:07:48 CST 2019
     */
    public void setChara(String chara) {
        this.chara = chara == null ? null : chara.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column general.people_num
     *
     * @return the value of general.people_num
     *
     * @mbg.generated Sat Jun 01 18:07:48 CST 2019
     */
    public String getPeopleNum() {
        return peopleNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column general.people_num
     *
     * @param peopleNum the value for general.people_num
     *
     * @mbg.generated Sat Jun 01 18:07:48 CST 2019
     */
    public void setPeopleNum(String peopleNum) {
        this.peopleNum = peopleNum == null ? null : peopleNum.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column general.vocation
     *
     * @return the value of general.vocation
     *
     * @mbg.generated Sat Jun 01 18:07:48 CST 2019
     */
    public String getVocation() {
        return vocation;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column general.vocation
     *
     * @param vocation the value for general.vocation
     *
     * @mbg.generated Sat Jun 01 18:07:48 CST 2019
     */
    public void setVocation(String vocation) {
        this.vocation = vocation == null ? null : vocation.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column general.address
     *
     * @return the value of general.address
     *
     * @mbg.generated Sat Jun 01 18:07:48 CST 2019
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column general.address
     *
     * @param address the value for general.address
     *
     * @mbg.generated Sat Jun 01 18:07:48 CST 2019
     */
    public void setAddress(String address) {
        this.address = address == null ? null : address.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column general.school
     *
     * @return the value of general.school
     *
     * @mbg.generated Sat Jun 01 18:07:48 CST 2019
     */
    public String getSchool() {
        return school;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column general.school
     *
     * @param school the value for general.school
     *
     * @mbg.generated Sat Jun 01 18:07:48 CST 2019
     */
    public void setSchool(String school) {
        this.school = school == null ? null : school.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column general.email
     *
     * @return the value of general.email
     *
     * @mbg.generated Sat Jun 01 18:07:48 CST 2019
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column general.email
     *
     * @param email the value for general.email
     *
     * @mbg.generated Sat Jun 01 18:07:48 CST 2019
     */
    public void setEmail(String email) {
        this.email = email == null ? null : email.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column general.tel_num
     *
     * @return the value of general.tel_num
     *
     * @mbg.generated Sat Jun 01 18:07:48 CST 2019
     */
    public String getTelNum() {
        return telNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column general.tel_num
     *
     * @param telNum the value for general.tel_num
     *
     * @mbg.generated Sat Jun 01 18:07:48 CST 2019
     */
    public void setTelNum(String telNum) {
        this.telNum = telNum == null ? null : telNum.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column general.content
     *
     * @return the value of general.content
     *
     * @mbg.generated Sat Jun 01 18:07:48 CST 2019
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column general.content
     *
     * @param content the value for general.content
     *
     * @mbg.generated Sat Jun 01 18:07:48 CST 2019
     */
    public void setContent(String content) {
        this.content = content == null ? null : content.trim();
    }

	@Override
	public String toString() {
		return "General [id=" + id + ", title=" + title + ", author=" + author + ", date=" + date + ", startDate="
				+ startDate + ", endDate=" + endDate + ", chara=" + chara + ", peopleNum=" + peopleNum + ", vocation="
				+ vocation + ", address=" + address + ", school=" + school + ", email=" + email + ", telNum=" + telNum
				+ ", content=" + content + "]";
	}
    
}