package com.heaven.bean;

public class GuidType {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column guid_type.id
     *
     * @mbg.generated Wed May 08 21:04:08 CST 2019
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column guid_type.type
     *
     * @mbg.generated Wed May 08 21:04:08 CST 2019
     */
    private String type;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column guid_type.id
     *
     * @return the value of guid_type.id
     *
     * @mbg.generated Wed May 08 21:04:08 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column guid_type.id
     *
     * @param id the value for guid_type.id
     *
     * @mbg.generated Wed May 08 21:04:08 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column guid_type.type
     *
     * @return the value of guid_type.type
     *
     * @mbg.generated Wed May 08 21:04:08 CST 2019
     */
    public String getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column guid_type.type
     *
     * @param type the value for guid_type.type
     *
     * @mbg.generated Wed May 08 21:04:08 CST 2019
     */
    public void setType(String type) {
        this.type = type == null ? null : type.trim();
    }
}