package com.heaven.bean;

import java.util.Date;

public class GuidInfo {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column guid_info.id
     *
     * @mbg.generated Thu May 09 23:50:36 CST 2019
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column guid_info.title
     *
     * @mbg.generated Thu May 09 23:50:36 CST 2019
     */
    private String title;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column guid_info.author
     *
     * @mbg.generated Thu May 09 23:50:36 CST 2019
     */
    private String author;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column guid_info.date
     *
     * @mbg.generated Thu May 09 23:50:36 CST 2019
     */
    private Date date;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column guid_info.type_id
     *
     * @mbg.generated Thu May 09 23:50:36 CST 2019
     */
    private Integer typeId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column guid_info.content
     *
     * @mbg.generated Thu May 09 23:50:36 CST 2019
     */
    private String content;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column guid_info.id
     *
     * @return the value of guid_info.id
     *
     * @mbg.generated Thu May 09 23:50:36 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column guid_info.id
     *
     * @param id the value for guid_info.id
     *
     * @mbg.generated Thu May 09 23:50:36 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column guid_info.title
     *
     * @return the value of guid_info.title
     *
     * @mbg.generated Thu May 09 23:50:36 CST 2019
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column guid_info.title
     *
     * @param title the value for guid_info.title
     *
     * @mbg.generated Thu May 09 23:50:36 CST 2019
     */
    public void setTitle(String title) {
        this.title = title == null ? null : title.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column guid_info.author
     *
     * @return the value of guid_info.author
     *
     * @mbg.generated Thu May 09 23:50:36 CST 2019
     */
    public String getAuthor() {
        return author;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column guid_info.author
     *
     * @param author the value for guid_info.author
     *
     * @mbg.generated Thu May 09 23:50:36 CST 2019
     */
    public void setAuthor(String author) {
        this.author = author == null ? null : author.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column guid_info.date
     *
     * @return the value of guid_info.date
     *
     * @mbg.generated Thu May 09 23:50:36 CST 2019
     */
    public Date getDate() {
        return date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column guid_info.date
     *
     * @param date the value for guid_info.date
     *
     * @mbg.generated Thu May 09 23:50:36 CST 2019
     */
    public void setDate(Date date) {
        this.date = date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column guid_info.type_id
     *
     * @return the value of guid_info.type_id
     *
     * @mbg.generated Thu May 09 23:50:36 CST 2019
     */
    public Integer getTypeId() {
        return typeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column guid_info.type_id
     *
     * @param typeId the value for guid_info.type_id
     *
     * @mbg.generated Thu May 09 23:50:36 CST 2019
     */
    public void setTypeId(Integer typeId) {
        this.typeId = typeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column guid_info.content
     *
     * @return the value of guid_info.content
     *
     * @mbg.generated Thu May 09 23:50:36 CST 2019
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column guid_info.content
     *
     * @param content the value for guid_info.content
     *
     * @mbg.generated Thu May 09 23:50:36 CST 2019
     */
    public void setContent(String content) {
        this.content = content == null ? null : content.trim();
    }

	@Override
	public String toString() {
		return "GuidInfo [id=" + id + ", title=" + title + ", author=" + author + ", date=" + date + ", typeId="
				+ typeId + ", content=" + content + "]";
	}
    
}