package com.heaven.bean;

public class Recruit {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column recruit.id
     *
     * @mbg.generated Sun Mar 31 17:05:13 CST 2019
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column recruit.recruit_name
     *
     * @mbg.generated Sun Mar 31 17:05:13 CST 2019
     */
    private String recruitName;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column recruit.id
     *
     * @return the value of recruit.id
     *
     * @mbg.generated Sun Mar 31 17:05:13 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column recruit.id
     *
     * @param id the value for recruit.id
     *
     * @mbg.generated Sun Mar 31 17:05:13 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column recruit.recruit_name
     *
     * @return the value of recruit.recruit_name
     *
     * @mbg.generated Sun Mar 31 17:05:13 CST 2019
     */
    public String getRecruitName() {
        return recruitName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column recruit.recruit_name
     *
     * @param recruitName the value for recruit.recruit_name
     *
     * @mbg.generated Sun Mar 31 17:05:13 CST 2019
     */
    public void setRecruitName(String recruitName) {
        this.recruitName = recruitName == null ? null : recruitName.trim();
    }
}