package com.heaven.bean;

public class TecType {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tec_type.id
     *
     * @mbg.generated Sun May 19 21:08:04 CST 2019
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tec_type.type_name
     *
     * @mbg.generated Sun May 19 21:08:04 CST 2019
     */
    private String typeName;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tec_type.id
     *
     * @return the value of tec_type.id
     *
     * @mbg.generated Sun May 19 21:08:04 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tec_type.id
     *
     * @param id the value for tec_type.id
     *
     * @mbg.generated Sun May 19 21:08:04 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tec_type.type_name
     *
     * @return the value of tec_type.type_name
     *
     * @mbg.generated Sun May 19 21:08:04 CST 2019
     */
    public String getTypeName() {
        return typeName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tec_type.type_name
     *
     * @param typeName the value for tec_type.type_name
     *
     * @mbg.generated Sun May 19 21:08:04 CST 2019
     */
    public void setTypeName(String typeName) {
        this.typeName = typeName == null ? null : typeName.trim();
    }
}