package com.heaven.bean;

public class VideoType {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column video_type.id
     *
     * @mbg.generated Sun May 19 21:08:04 CST 2019
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column video_type.type_name
     *
     * @mbg.generated Sun May 19 21:08:04 CST 2019
     */
    private String typeName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column video_type.tec_type_id
     *
     * @mbg.generated Sun May 19 21:08:04 CST 2019
     */
    private Integer tecTypeId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column video_type.id
     *
     * @return the value of video_type.id
     *
     * @mbg.generated Sun May 19 21:08:04 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column video_type.id
     *
     * @param id the value for video_type.id
     *
     * @mbg.generated Sun May 19 21:08:04 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column video_type.type_name
     *
     * @return the value of video_type.type_name
     *
     * @mbg.generated Sun May 19 21:08:04 CST 2019
     */
    public String getTypeName() {
        return typeName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column video_type.type_name
     *
     * @param typeName the value for video_type.type_name
     *
     * @mbg.generated Sun May 19 21:08:04 CST 2019
     */
    public void setTypeName(String typeName) {
        this.typeName = typeName == null ? null : typeName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column video_type.tec_type_id
     *
     * @return the value of video_type.tec_type_id
     *
     * @mbg.generated Sun May 19 21:08:04 CST 2019
     */
    public Integer getTecTypeId() {
        return tecTypeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column video_type.tec_type_id
     *
     * @param tecTypeId the value for video_type.tec_type_id
     *
     * @mbg.generated Sun May 19 21:08:04 CST 2019
     */
    public void setTecTypeId(Integer tecTypeId) {
        this.tecTypeId = tecTypeId;
    }
}