package com.heaven.bean;

public class Video {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column video.id
     *
     * @mbg.generated Thu May 23 20:59:58 CST 2019
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column video.title
     *
     * @mbg.generated Thu May 23 20:59:58 CST 2019
     */
    private String title;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column video.description
     *
     * @mbg.generated Thu May 23 20:59:58 CST 2019
     */
    private String description;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column video.path
     *
     * @mbg.generated Thu May 23 20:59:58 CST 2019
     */
    private String path;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column video.time
     *
     * @mbg.generated Thu May 23 20:59:58 CST 2019
     */
    private String time;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column video.image
     *
     * @mbg.generated Thu May 23 20:59:58 CST 2019
     */
    private String image;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column video.video_type_id
     *
     * @mbg.generated Thu May 23 20:59:58 CST 2019
     */
    private Integer videoTypeId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column video.id
     *
     * @return the value of video.id
     *
     * @mbg.generated Thu May 23 20:59:58 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column video.id
     *
     * @param id the value for video.id
     *
     * @mbg.generated Thu May 23 20:59:58 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column video.title
     *
     * @return the value of video.title
     *
     * @mbg.generated Thu May 23 20:59:58 CST 2019
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column video.title
     *
     * @param title the value for video.title
     *
     * @mbg.generated Thu May 23 20:59:58 CST 2019
     */
    public void setTitle(String title) {
        this.title = title == null ? null : title.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column video.description
     *
     * @return the value of video.description
     *
     * @mbg.generated Thu May 23 20:59:58 CST 2019
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column video.description
     *
     * @param description the value for video.description
     *
     * @mbg.generated Thu May 23 20:59:58 CST 2019
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column video.path
     *
     * @return the value of video.path
     *
     * @mbg.generated Thu May 23 20:59:58 CST 2019
     */
    public String getPath() {
        return path;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column video.path
     *
     * @param path the value for video.path
     *
     * @mbg.generated Thu May 23 20:59:58 CST 2019
     */
    public void setPath(String path) {
        this.path = path == null ? null : path.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column video.time
     *
     * @return the value of video.time
     *
     * @mbg.generated Thu May 23 20:59:58 CST 2019
     */
    public String getTime() {
        return time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column video.time
     *
     * @param time the value for video.time
     *
     * @mbg.generated Thu May 23 20:59:58 CST 2019
     */
    public void setTime(String time) {
        this.time = time == null ? null : time.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column video.image
     *
     * @return the value of video.image
     *
     * @mbg.generated Thu May 23 20:59:58 CST 2019
     */
    public String getImage() {
        return image;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column video.image
     *
     * @param image the value for video.image
     *
     * @mbg.generated Thu May 23 20:59:58 CST 2019
     */
    public void setImage(String image) {
        this.image = image == null ? null : image.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column video.video_type_id
     *
     * @return the value of video.video_type_id
     *
     * @mbg.generated Thu May 23 20:59:58 CST 2019
     */
    public Integer getVideoTypeId() {
        return videoTypeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column video.video_type_id
     *
     * @param videoTypeId the value for video.video_type_id
     *
     * @mbg.generated Thu May 23 20:59:58 CST 2019
     */
    public void setVideoTypeId(Integer videoTypeId) {
        this.videoTypeId = videoTypeId;
    }

	@Override
	public String toString() {
		return "Video [id=" + id + ", title=" + title + ", description=" + description + ", path=" + path + ", time="
				+ time + ", image=" + image + ", videoTypeId=" + videoTypeId + "]";
	}
    
}