package com.heaven.dao;

import com.heaven.bean.General;
import com.heaven.bean.GeneralExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface GeneralMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table general
     *
     * @mbg.generated Thu May 09 23:50:36 CST 2019
     */
    long countByExample(GeneralExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table general
     *
     * @mbg.generated Thu May 09 23:50:36 CST 2019
     */
    int deleteByExample(GeneralExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table general
     *
     * @mbg.generated Thu May 09 23:50:36 CST 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table general
     *
     * @mbg.generated Thu May 09 23:50:36 CST 2019
     */
    int insert(General record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table general
     *
     * @mbg.generated Thu May 09 23:50:36 CST 2019
     */
    int insertSelective(General record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table general
     *
     * @mbg.generated Thu May 09 23:50:36 CST 2019
     */
    List<General> selectByExampleWithBLOBs(GeneralExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table general
     *
     * @mbg.generated Thu May 09 23:50:36 CST 2019
     */
    List<General> selectByExample(GeneralExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table general
     *
     * @mbg.generated Thu May 09 23:50:36 CST 2019
     */
    General selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table general
     *
     * @mbg.generated Thu May 09 23:50:36 CST 2019
     */
    int updateByExampleSelective(@Param("record") General record, @Param("example") GeneralExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table general
     *
     * @mbg.generated Thu May 09 23:50:36 CST 2019
     */
    int updateByExampleWithBLOBs(@Param("record") General record, @Param("example") GeneralExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table general
     *
     * @mbg.generated Thu May 09 23:50:36 CST 2019
     */
    int updateByExample(@Param("record") General record, @Param("example") GeneralExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table general
     *
     * @mbg.generated Thu May 09 23:50:36 CST 2019
     */
    int updateByPrimaryKeySelective(General record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table general
     *
     * @mbg.generated Thu May 09 23:50:36 CST 2019
     */
    int updateByPrimaryKeyWithBLOBs(General record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table general
     *
     * @mbg.generated Thu May 09 23:50:36 CST 2019
     */
    int updateByPrimaryKey(General record);
}