package com.heaven.dao;

import com.heaven.bean.GuidInfo;
import com.heaven.bean.GuidInfoExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface GuidInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table guid_info
     *
     * @mbg.generated Thu May 09 23:50:36 CST 2019
     */
    long countByExample(GuidInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table guid_info
     *
     * @mbg.generated Thu May 09 23:50:36 CST 2019
     */
    int deleteByExample(GuidInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table guid_info
     *
     * @mbg.generated Thu May 09 23:50:36 CST 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table guid_info
     *
     * @mbg.generated Thu May 09 23:50:36 CST 2019
     */
    int insert(GuidInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table guid_info
     *
     * @mbg.generated Thu May 09 23:50:36 CST 2019
     */
    int insertSelective(GuidInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table guid_info
     *
     * @mbg.generated Thu May 09 23:50:36 CST 2019
     */
    List<GuidInfo> selectByExampleWithBLOBs(GuidInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table guid_info
     *
     * @mbg.generated Thu May 09 23:50:36 CST 2019
     */
    List<GuidInfo> selectByExample(GuidInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table guid_info
     *
     * @mbg.generated Thu May 09 23:50:36 CST 2019
     */
    GuidInfo selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table guid_info
     *
     * @mbg.generated Thu May 09 23:50:36 CST 2019
     */
    int updateByExampleSelective(@Param("record") GuidInfo record, @Param("example") GuidInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table guid_info
     *
     * @mbg.generated Thu May 09 23:50:36 CST 2019
     */
    int updateByExampleWithBLOBs(@Param("record") GuidInfo record, @Param("example") GuidInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table guid_info
     *
     * @mbg.generated Thu May 09 23:50:36 CST 2019
     */
    int updateByExample(@Param("record") GuidInfo record, @Param("example") GuidInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table guid_info
     *
     * @mbg.generated Thu May 09 23:50:36 CST 2019
     */
    int updateByPrimaryKeySelective(GuidInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table guid_info
     *
     * @mbg.generated Thu May 09 23:50:36 CST 2019
     */
    int updateByPrimaryKeyWithBLOBs(GuidInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table guid_info
     *
     * @mbg.generated Thu May 09 23:50:36 CST 2019
     */
    int updateByPrimaryKey(GuidInfo record);
}