package com.heaven.dao;

import com.heaven.bean.TecType;
import com.heaven.bean.TecTypeExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TecTypeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tec_type
     *
     * @mbg.generated Sun May 19 21:08:04 CST 2019
     */
    long countByExample(TecTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tec_type
     *
     * @mbg.generated Sun May 19 21:08:04 CST 2019
     */
    int deleteByExample(TecTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tec_type
     *
     * @mbg.generated Sun May 19 21:08:04 CST 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tec_type
     *
     * @mbg.generated Sun May 19 21:08:04 CST 2019
     */
    int insert(TecType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tec_type
     *
     * @mbg.generated Sun May 19 21:08:04 CST 2019
     */
    int insertSelective(TecType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tec_type
     *
     * @mbg.generated Sun May 19 21:08:04 CST 2019
     */
    List<TecType> selectByExample(TecTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tec_type
     *
     * @mbg.generated Sun May 19 21:08:04 CST 2019
     */
    TecType selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tec_type
     *
     * @mbg.generated Sun May 19 21:08:04 CST 2019
     */
    int updateByExampleSelective(@Param("record") TecType record, @Param("example") TecTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tec_type
     *
     * @mbg.generated Sun May 19 21:08:04 CST 2019
     */
    int updateByExample(@Param("record") TecType record, @Param("example") TecTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tec_type
     *
     * @mbg.generated Sun May 19 21:08:04 CST 2019
     */
    int updateByPrimaryKeySelective(TecType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tec_type
     *
     * @mbg.generated Sun May 19 21:08:04 CST 2019
     */
    int updateByPrimaryKey(TecType record);
}