package com.heaven.dao;

import com.heaven.bean.UserType;
import com.heaven.bean.UserTypeExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface UserTypeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_type
     *
     * @mbg.generated Sat Apr 13 00:37:32 CST 2019
     */
    long countByExample(UserTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_type
     *
     * @mbg.generated Sat Apr 13 00:37:32 CST 2019
     */
    int deleteByExample(UserTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_type
     *
     * @mbg.generated Sat Apr 13 00:37:32 CST 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_type
     *
     * @mbg.generated Sat Apr 13 00:37:32 CST 2019
     */
    int insert(UserType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_type
     *
     * @mbg.generated Sat Apr 13 00:37:32 CST 2019
     */
    int insertSelective(UserType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_type
     *
     * @mbg.generated Sat Apr 13 00:37:32 CST 2019
     */
    List<UserType> selectByExample(UserTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_type
     *
     * @mbg.generated Sat Apr 13 00:37:32 CST 2019
     */
    UserType selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_type
     *
     * @mbg.generated Sat Apr 13 00:37:32 CST 2019
     */
    int updateByExampleSelective(@Param("record") UserType record, @Param("example") UserTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_type
     *
     * @mbg.generated Sat Apr 13 00:37:32 CST 2019
     */
    int updateByExample(@Param("record") UserType record, @Param("example") UserTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_type
     *
     * @mbg.generated Sat Apr 13 00:37:32 CST 2019
     */
    int updateByPrimaryKeySelective(UserType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_type
     *
     * @mbg.generated Sat Apr 13 00:37:32 CST 2019
     */
    int updateByPrimaryKey(UserType record);
}