package com.heaven.dao;

import com.heaven.bean.VideoComment;
import com.heaven.bean.VideoCommentExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface VideoCommentMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table video_comment
     *
     * @mbg.generated Sun May 19 21:08:04 CST 2019
     */
    long countByExample(VideoCommentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table video_comment
     *
     * @mbg.generated Sun May 19 21:08:04 CST 2019
     */
    int deleteByExample(VideoCommentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table video_comment
     *
     * @mbg.generated Sun May 19 21:08:04 CST 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table video_comment
     *
     * @mbg.generated Sun May 19 21:08:04 CST 2019
     */
    int insert(VideoComment record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table video_comment
     *
     * @mbg.generated Sun May 19 21:08:04 CST 2019
     */
    int insertSelective(VideoComment record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table video_comment
     *
     * @mbg.generated Sun May 19 21:08:04 CST 2019
     */
    List<VideoComment> selectByExample(VideoCommentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table video_comment
     *
     * @mbg.generated Sun May 19 21:08:04 CST 2019
     */
    VideoComment selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table video_comment
     *
     * @mbg.generated Sun May 19 21:08:04 CST 2019
     */
    int updateByExampleSelective(@Param("record") VideoComment record, @Param("example") VideoCommentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table video_comment
     *
     * @mbg.generated Sun May 19 21:08:04 CST 2019
     */
    int updateByExample(@Param("record") VideoComment record, @Param("example") VideoCommentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table video_comment
     *
     * @mbg.generated Sun May 19 21:08:04 CST 2019
     */
    int updateByPrimaryKeySelective(VideoComment record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table video_comment
     *
     * @mbg.generated Sun May 19 21:08:04 CST 2019
     */
    int updateByPrimaryKey(VideoComment record);
}